### ISSUE TITLE
Singleton Type not preferred for Winget

### ISSUE THREAD

**Issue by Trenly** [pulumi/pulumi-winget#1]
https://github.com/pulumi/pulumi-winget/blob/d639b955958986ee88b831bee3e5ff6e6bc26c3d/src/Program.fs#L81

With the [1.1.0 schema](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.1.0) released and the [1.2.0](https://github.com/microsoft/winget-cli/tree/master/schemas/JSON/manifests/v1.2.0) schema on the way, the amount of metadata which can be included with releases is growing. Because of this, Singleton manifests are not preferred. To stay ahead of the curve, pulumi should probably consider upgrading to manifest version 1.1.0 using the multi-file structure.

https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.1.0/singleton.md?plain=1#L19

**Comment by vedantmgoyal2009** [comment]
You can replace the manifest creation and submission part with my action.

Example: https://github.com/LinwoodCloud/Butterfly/blob/develop/.github/workflows/winget.yml

**Comment by Zaid-Ajaj** [comment]
@Trenly @vedantmgoyal2009 According to [this comment](https://github.com/pulumi/pulumi/issues/4676#issuecomment-1079362766), the singleton manifest is going to stay for a long time so an update doesn't seem necessary at the moment. 

@vedantmgoyal2009 The reason we do manifest creation ourselves here is to be able to reuse the [product code](https://github.com/pulumi/pulumi-winget/blob/master/src/Program.fs#L159) both in the manifest and Wix installer definition

**Comment by vedantmgoyal2009** [comment]
> @vedantmgoyal2009 The reason we do manifest creation ourselves here is to be able to reuse the [product code](https://github.com/pulumi/pulumi-winget/blob/master/src/Program.fs?rgh-link-date=2022-05-06T14%3A15%3A06Z#L159) both in the manifest and Wix installer definition

The action will find the product code from the MSI database itself, so you don't need to worry about different product codes in MSI and Manifest.

**Comment by Trenly** [comment]
> @Trenly @vedantmgoyal2009 According to [this comment](https://github.com/pulumi/pulumi/issues/4676#issuecomment-1079362766), the singleton manifest is going to stay for a long time so an update doesn't seem necessary at the moment.
> 
> @vedantmgoyal2009 The reason we do manifest creation ourselves here is to be able to reuse the [product code](https://github.com/pulumi/pulumi-winget/blob/master/src/Program.fs#L159) both in the manifest and Wix installer definition

While it may not be "Soon", using the Multi-Manifest format is preferred because as newer manifest versions are released, which contain fields for additional metadata, the Multi-Manifest structure makes it easier to read and verify. It also allows for winget community contributions for localized description files, etc.
