### ISSUE TITLE
Publish checksums of the MSI files

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-winget#14]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

An enterprise prospect can't whitelist the Pulumi software according their own company rules. For them, one of the following two rules need to be fullfilled for Pulumi to be accepted for distribution on their Windows machines:

* Only the installer (MSI) is signed as it proves it has been generated by the developer.
* Aside with the installer / MSI download location, there is a documented MD5 / SHA checksum that we can validate to confirm the same.

While full code signing might be a good long term solution, can we have the MSI checksums published in this project as a short term fix?

### Affected area/feature

CLI on Windows - increasing the software supply chain security.

**Comment by RobbieMcKinstry** [comment]
cc: @AaronFriel and @Zaid-Ajaj, who have bounced around ideas in Slack.
